### ISSUE TITLE
ghc-8.2.0-rc1 compilation error

### ISSUE THREAD

**Issue by alexanderkjeldaas** [haskell/deepseq#34]
```
    Configuring deepseq-1.4.2.0...
    Preprocessing library for deepseq-1.4.2.0..
    Building library for deepseq-1.4.2.0..
    [1 of 1] Compiling Control.DeepSeq  ( Control/DeepSeq.hs, .stack-work/dist/x86_64-osx/Cabal-2.0.0.0/build/Control/DeepSeq.o )

    /private/var/folders/pq/xz5t60ld4v10j_tt7bd25rfhtzqwq8/T/stack92873/deepseq-1.4.2.0/Control/DeepSeq.hs:420:10: error:
        • Illegal instance declaration for ‘NFData TypeRep’
            (All instance types must be of the form (T t1 ... tn)
             where T is not a synonym.
             Use TypeSynonymInstances if you want to disable this.)
        • In the instance declaration for ‘NFData TypeRep’
        |
    420 | instance NFData TypeRep where
        |          ^^^^^^^^^^^^^^
```

**Comment by alexanderkjeldaas** [comment]
using the stack setup:

```
compiler: ghc-8.2.0.20170404
compiler-check: match-exact
setup-info:
  ghc:
    linux64:
      8.2.0.20170404:
        url: https://downloads.haskell.org/~ghc/8.2.1-rc1/ghc-8.2.0.20170404-x86_64-deb8-linux.tar.xz
        content-length: 138846620
        sha1: 3fd303b5753b095ce020131405dcf43199e6b447
    macosx:
      8.2.0.20170404:
        url: https://downloads.haskell.org/~ghc/8.2.1-rc1/ghc-8.2.0.20170404-x86_64-apple-darwin.tar.xz
        content-length: 124010408
        sha1: 301de7f5b6ed87ade2182ed2552df2ef39b98b03
    # The Windows build is broken :(
    # https://www.reddit.com/r/haskell/comments/64he68/announce_ghc_821_release_candidate_1/dg2b5ei/
    windows64:
      8.2.0.20170404:
        url: https://downloads.haskell.org/~ghc/8.2.1-rc1/ghc-8.2.0.20170404-x86_64-unknown-mingw32.tar.xz
        content-length: 173924808
        sha1: 5cfd11230ff95423a7b19104232247e3fab0dba3
```

**Comment by alexanderkjeldaas** [comment]
I guess this is already fixed in `master`.

I'll show myself out. thanks.

**Comment by hvr** [comment]
@alexanderkjeldaas Fwiw, `deepseq-1.4.2` has an upper bound `base < 4.10` (while GHC 8.2 comes with an non-upgradable `base-4.11`), if Stack doesn't honor that version constraint, you should file a bug upstream.

**Comment by kolmodin** [comment]
@hvr Can you release a new version of deepseq? It would make testing GHC 8.2.0-rc1 a lot easier. If there are no versions of deepseq that works with the latest RC it's harder to test :) 
Thanks Herbert!

**Comment by hvr** [comment]
@kolmodin I'm not sure what you mean. `deepseq` is bundled with GHC, so if you install GHC 8.2.0-rc1 you automatically get the "rc" version of `deepseq` as well. I've also updated the release-candidate of `deepseq` over  at http://hackage.haskell.org/package/deepseq-1.4.3.0/candidate

**Comment by kolmodin** [comment]
Oh, cool, I did not know about candidates on hackage. I'll read up on that.

So the issue that Alexander has was stack specific then? It's supposed to make use of the deepseq version that comes with GHC, but (maybe) the Stack LTS pins another version? Hmm. Ok.

Good that it's supposed to work for cabal users at least, it's frustrating when some packages hinder testing new versions of GHC.
So, false alarm, thanks for the clarification!

**Comment by hvr** [comment]
@kolmodin Yeah, what Alexander was experiencing seems rather like a Stack bug to me, as `deepseq-1.4.2.0`'s meta-data explicitly states that it excludes GHC 8.2.0RC's `base-4.11`. For reference, here's what a recent GHC 8.2 snapshot contains in its global database out of the box (and that's gonna change slightly for RC2, as not all libraries had been finalised when RC1 was cut):

```
$ ghc-pkg-8.2.1 list
/opt/ghc/8.2.1/lib/ghc-8.2.0.20170413/package.conf.d
    Cabal-2.0.0.0
    array-0.5.1.2
    base-4.10.0.0
    binary-0.8.5.1
    bytestring-0.10.8.2
    containers-0.5.10.2
    deepseq-1.4.3.0
    directory-1.3.0.2
    filepath-1.4.1.1
    ghc-8.2.0.20170413
    ghc-boot-8.2.0.20170413
    ghc-boot-th-8.2.0.20170413
    ghc-compact-0.1.0.0
    ghc-prim-0.5.0.0
    ghci-8.2.0.20170413
    haskeline-0.7.3.1
    hoopl-3.10.2.2
    hpc-0.6.0.3
    integer-gmp-1.0.0.1
    pretty-1.1.3.3
    process-1.4.3.0
    rts-1.0
    template-haskell-2.12.0.0
    terminfo-0.4.0.2
    time-1.8.0.1
    transformers-0.5.2.0
    unix-2.7.2.1
    xhtml-3000.2.1
```

**Comment by snoyberg** [comment]
I got linked here from Twitter. When reviewing, I _think_ the Stack repro is incomplete. If I use the above `stack.yaml` and run:

    stack build deepseq --install-ghc

I get:

```
Could not parse '/Users/michael/Desktop/deepseq34/stack.yaml':
Aeson exception:
Error in $: failed to parse field 'resolver': key "resolver" not present
See http://docs.haskellstack.org/en/stable/yaml_configuration/
```

I'm going to guess that there was an additional `resolver` line in the config file, such as `resolver: lts-8.9`. Adding that line (and also `packages: []` since I don't have any local packages), I get the following output now:

```
Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for array-0.5.1.1:
    base-4.10.0.0 must match >=4.5 && <4.10 (latest applicable is 4.9.1.0)

In the dependencies for deepseq-1.4.2.0:
    base-4.10.0.0 must match >=4.3 && <4.10 (latest applicable is 4.9.1.0)

Plan construction failed.
```

All of this with:

```
$ stack --version
Version 1.4.0, Git revision e714f1dd3fade19496d91bd6a017e435a96a6bcd (4640 commits) x86_64 hpack-0.17.0
```

If I _additionally_ add `allow-newer: true` to the `stack.yaml`, then I get the error message you provided above @alexanderkjeldaas. Obviously this is acceptable behavior by Stack, since you explicitly asked for newer versions to be allowed (same as the `cabal-install` flag). The only other thing I wanted to point out here is _why_ Stack is insisting on installing a new `deepseq` in this case instead of using the one in the global database.

Stack and Stackage take a very limited definition of wired-in packages to allow as many packages to upgrade as possible. This essentially comes down to "anything which is a direct or indirect dependency of the ghc and template-haskell packages," since those cannot be upgraded at all. `deepseq` doesn't fall into this definition, and therefore Stackage snapshots specify precise versions of it, regardless of what GHC ships with. For more information, see https://github.com/fpco/stackage/issues/395. In this case, the `lts-8.9` snapshot defines a version of `deepseq` which is incompatible with GHC 8.2. 

Workarounds:

* Don't use a Stackage snapshot, but instead use something like `stack solver` from an empty GHC resolver
* Specify which version of deepseq to use as an extra-dep (if the relevant one was available on Hackage, which is not the case here)
* Use the Git package support, such as with the following:

```yaml
- location:
    git: https://github.com/haskell/deepseq.git
    commit: 0b22c9825ef79c1ee41d2f19e7c997f5cdc93494
  extra-dep: true
```
